config/routes.rb
Rails.application.routes.draw do

  
  namespace :public do
    get 'order_details/new'
  end
root to: 'public/homes#top'
get 'about' => 'public/homes#about'
get 'items' => 'public/items#index'
get 'items/:id' => 'public/items#show', as: 'item'
post 'cart_items' => 'public/cart_items#create'
get 'cart_items' => 'public/cart_items#index'
patch 'cart_items' => 'public/cart_items#update'

delete 'cart_items/:id' => 'public/cart_items#destroy', as: 'destroy_cart_item'
delete 'cart_items' => 'public/cart_items#destroy_all', as: 'cart_items_destroy_all'


get 'orders/new' => 'public/orders#new'
post 'orders/comfirm' => 'public/orders#comfirm'
post 'orders' => 'public/orders#create'
get 'orders/complete' => 'public/orders#complete'
get 'orders' => 'public/orders#index', as: 'orders_index'
get 'orders/:id' => 'public/orders#show', as: 'order'

  scope module: 'public' do
    get 'customers/edit/:id' => 'customers#edit', as: 'edit_customer'
    patch 'customers' => 'customers#update', as: 'customer'
    get 'customers/my_page' => 'customers#show'
    get 'customers/unsubscribe' => 'customers#unsubscribe'
    patch 'customers/withdraw'
   end
  get 'addresses' => 'public/addresses#index'
  get 'addresses/:id/edit' => 'public/addresses#edit'
  post 'addresses' => 'public/addresses#create'
  patch 'addresses/:id' => 'public/addresses#update'
  delete 'addresses/:id' => 'public/addresses#destroy'

  namespace :admin do
    get 'orders/index'
  end
#  devise_for :admins
    devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
    }
  namespace :admin do
    resources :customers, only: [:index, :show, :edit, :update]
  end
  namespace :admin do
    resources :genres
  end
  namespace :admin do
    resources :items
  end
  namespace :admin do
    get 'top' => 'homes#top'
  end
  namespace :admin do
    resources :orders
  end
  devise_for :customers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord


  belongs_to :item
  belongs_to :customer

  #def total_price
	#	line_items.to_a.sum { |item| item.total_price }
	#end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses
  has_many :orders
  has_many :cart_items
  
  def active_for_authentication?
    super && (self.is_active == false)
  end
  
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :item, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
    
    attachment :image
    belongs_to :genre,  optional: true
    has_many :cart_items
  #  has_many :orders
    has_many :order_details
end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :customer
  has_many :order_details
  enum payment_method: { クレジットカード: 0, 銀行振込: 1 }
  enum status: { 入金待ち: 0, 入金確認: 1, 製作中: 2, 発送準備中: 3, 発送済み: 4 }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customer = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end
  
  def update
    @customer = Customer.find(params[:id])

      if @customer.update(customer_params)
        flash[:notice]="Book was successfully updated."
        redirect_to admin_customers_path
      else
        render :edit
      end
  end
  
  private
  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :postal_code, :address, :telephone_number)
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
 def index
    @genre = Genre.all
 end

 def edit
      @genre = Genre.find(params[:id])
 end

 def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
 end

 def update
  @genre = Genre.find(params[:id])
  @genre.update(genre_params)
  redirect_to admin_genres_path
 end

 def destroy
   @genre = Genre.find(params[:id])
   @genre.destroy
   redirect_to admin_genres_path
 end

  def new
    @genre = Genre.new
  end

 private
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @order = Order.all
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @item = Item.all
    @genre = Genre.all

  end

  def new
    @item = Item.new
    @genre = Genre.all
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
    @genre = Genre.all
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item)
  end

  def update
   @item = Item.find(params[:id])
   @item.update(item_params)
   redirect_to admin_item_path
  end


 private
  def item_params
    params.require(:item).permit(:genre_id, :name, :introduction, :price, :image)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :postal_code, :address, :telephone_number, :is_deleted,])
  end
  
  def after_sign_in_path_for(resource)
    root_path
  end

  def after_sign_out_path_for(resource)
    root_path
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
  <div class="row">
   <div class="col-lx-1">
     <h1>お客様情報変更</h1>
     
     <%= form_with model:@customer, url:admin_customer_path, local:true do |f| %>
     <h3><%= f.label :姓 %><%= f.label :名 %></h3>
     <%= f.text_field :last_name, placeholder:"姓" %><%= f.text_field :first_name, placeholder:"名" %>
     <br><br>
     
     <h3><%= f.label :姓（カナ） %><%= f.label :名（カナ） %></h3>
     <%= f.text_field :last_name_kana, placeholder:"姓（カナ）" %><%= f.text_field :first_name_kana, placeholder:"名（カナ）" %>
     <br><br>
     
     <h3><%= f.label :メールアドレス %></h3>
     <%= f.text_field :email, placeholder:"email" %>
     
     
     <h3><%= f.label :郵便番号 %></h3>
     <%= f.text_field :postal_code, placeholder:"郵便番号" %>
     
     <h3><%= f.label :住所 %></h3>
     <%= f.text_field :address, placeholder:"住所" %>
     
     <h3><%= f.label :電話番号 %></h3>
     <%= f.text_field :telephone_number, placeholder:"電話番号" %>
     
     <h3><%= f.label :会員ステータス %></h3>
     <%= f.text_field :is_active, placeholder:"ステータス" %>
     
     
  <br><br>
  <%= f.submit "Update" %>
<% end %>
</div>
</div>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row">

<!-- サイドバー終わり -->

<div class="col-mx-1">
<h1>User detail</h1>
      <table class="table user-show">

		<th>last_name</th>
		<th>first_name</th>
		<th>last_name_kana</th>
		<th>first_name_kana</th>
		<th>email</th>
		<th>postal_code</th>
		<th>address</th>
		<th>telephone_number</th>
		<th>is_deleted</th>
		<th>created_at</th>
		<th>updated_at</th>
		<th></th>
         <% @customer.each do |customer| %>
            <tr>
            	
				<td><%= link_to admin_customer_path(customer) do %>
					<%= customer.last_name %>
					<% end %>
					</td>
				<td><%= link_to admin_customer_path(customer) do %>
					<%= customer.first_name %></td>
				<% end %>
				<td><%= customer.last_name_kana %></td>
				<td><%= customer.first_name_kana %></td>
				<td><%= customer.email %></td>
				<td><%= customer.postal_code %></td>
				<td><%= customer.address %></td>
				<td><%= customer.telephone_number %></td>
				<td>
					<% if customer.is_active %>
          退会済み
          <% else %>
          -
          <% end %>
					<%#= customer.is_active %></td>
				<td><%= customer.created_at.strftime('%Y/%m/%d %H:%M') %></td>
				<td><%= customer.updated_at.strftime('%Y/%m/%d %H:%M') %></td>
				<td><%= link_to "Edit",  edit_admin_customer_path(customer), class:"btn btn-success"%></td>
				<% end %>
          </tr>
        </table>
</div>
</div>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-mx-1">
      <h1>Customers detail</h1>


      <p>名前（カナ）</p>
      <%= @customer.last_name_kana %><%= @customer.first_name_kana %>
      <p>名前</p>
      <%= @customer.last_name %><%= @customer.first_name %>

      <p>メールアドレス</p>
      <%= @customer.email %>
      <p>郵便番号</p>
      <%= @customer.postal_code %>
      <p>住所</p>
      <%= @customer.address %>
      <p>電話番号</p>
      <%= @customer.telephone_number %>
      <p>登録日時</p>
      <%= @customer.created_at.strftime('%Y/%m/%d %H:%M') %>
      <p>更新日時</p>
      <%= @customer.updated_at.strftime('%Y/%m/%d %H:%M') %>
      <br>
      <%= link_to "Edit",  edit_admin_customer_path(@customer), class:"btn btn-success"%>
    </div>
  </div>
</div>