config/routes.rb
Rails.application.routes.draw do

  
  namespace :public do
    get 'order_details/new'
  end
root to: 'public/homes#top'
get 'about' => 'public/homes#about'
get 'items' => 'public/items#index'
get 'items/:id' => 'public/items#show', as: 'item'
post 'cart_items' => 'public/cart_items#create'
get 'cart_items' => 'public/cart_items#index'
patch 'cart_items' => 'public/cart_items#update'

delete 'cart_items/:id' => 'public/cart_items#destroy', as: 'destroy_cart_item'
delete 'cart_items' => 'public/cart_items#destroy_all', as: 'cart_items_destroy_all'


get 'orders/new' => 'public/orders#new'
post 'orders/comfirm' => 'public/orders#comfirm'
post 'orders' => 'public/orders#create'
get 'orders/complete' => 'public/orders#complete'
get 'orders' => 'public/orders#index', as: 'orders_index'
get 'orders/:id' => 'public/orders#show', as: 'order'

  scope module: 'public' do
    get 'customers/edit/:id' => 'customers#edit', as: 'edit_customer'
    patch 'customers' => 'customers#update', as: 'customer'
    get 'customers/my_page' => 'customers#show'
    get 'customers/unsubscribe' => 'customers#unsubscribe'
    patch 'customers/withdraw'
   end
  get 'addresses' => 'public/addresses#index'
  get 'addresses/:id/edit' => 'public/addresses#edit'
  post 'addresses' => 'public/addresses#create'
  patch 'addresses/:id' => 'public/addresses#update'
  delete 'addresses/:id' => 'public/addresses#destroy'

  namespace :admin do
    get 'orders/index'
  end
#  devise_for :admins
    devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
    }
  namespace :admin do
    resources :customers, only: [:index, :show, :edit, :update]
  end
  namespace :admin do
    resources :genres
  end
  namespace :admin do
    resources :items
  end
  namespace :admin do
    get 'top' => 'homes#top'
  end
  namespace :admin do
    resources :orders
  end
  devise_for :customers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord


  belongs_to :item
  belongs_to :customer

  #def total_price
	#	line_items.to_a.sum { |item| item.total_price }
	#end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses
  has_many :orders
  has_many :cart_items
  
  def active_for_authentication?
    super && (self.is_active == false)
  end
  
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :item, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
    
    attachment :image
    belongs_to :genre,  optional: true
    has_many :cart_items
  #  has_many :orders
    has_many :order_details
end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :customer
  has_many :order_details
  enum payment_method: { クレジットカード: 0, 銀行振込: 1 }
  enum status: { 入金待ち: 0, 入金確認: 1, 製作中: 2, 発送準備中: 3, 発送済み: 4 }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
 def index
    @genre = Genre.all
 end

 def edit
      @genre = Genre.find(params[:id])
 end

 def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
 end

 def update
  @genre = Genre.find(params[:id])
  @genre.update(genre_params)
  redirect_to admin_genres_path
 end

 def destroy
   @genre = Genre.find(params[:id])
   @genre.destroy
   redirect_to admin_genres_path
 end

  def new
    @genre = Genre.new
  end

 private
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @order = Order.all
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @item = Item.all
    @genre = Genre.all

  end

  def new
    @item = Item.new
    @genre = Genre.all
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
    @genre = Genre.all
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item)
  end

  def update
   @item = Item.find(params[:id])
   @item.update(item_params)
   redirect_to admin_item_path
  end


 private
  def item_params
    params.require(:item).permit(:genre_id, :name, :introduction, :price, :image)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def index
    @order = Order.all
  end
  
  def show
    @order = Order.find(params[:id])
  @order_details = OrderDetail.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :postal_code, :address, :telephone_number, :is_deleted,])
  end
  
  def after_sign_in_path_for(resource)
    root_path
  end

  def after_sign_out_path_for(resource)
    root_path
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/genres/edit.html.erb
<div class="container">
  <div class="row">

   <div class="col-md-3">
<h1>Editing Genre</h1>



<%= form_with model:@genre, url:admin_genre_path, local:true do |f| %>

  <h3><%= f.label :Genre %><br></h3>
  <%= f.text_field :name %>
  <br><br>
  <%= f.submit 'Update Genre' %>
  <br><br>
  <%= link_to "Show", admin_genres_path, class:"btn btn-info" %>
  |
  <%= link_to "Back", admin_genres_path, class:"btn btn-primary" %>
  |
  <%= link_to "Destroy", admin_genre_path(@genre), method: :delete, data: {confirm: "消しますか？"}, class:"btn btn-danger" %>


<% end %>
</div>
</div>
</div>

app/views/admin/genres/index.html.erb
<div class="container">
  <div class="row">

   <div class="col-md-3">
     <h1>Genres</h1>

<div class="genres">

<!-- サイドバー -->

<h1>New Genre</h1>
<%= form_with(model:@genre, url:admin_genres_path, method: :POST, local:true) do |f| %>

<div>
  <%= f.label :Genre %>
</div>
<div>
  <%= f.text_field :name %>
</div>
</div>
<br>
<%= f.submit 'Create Genre' %>
<% end %>
  


    </div>

<!-- サイドバー終わり -->

<div class="col-md-9">
<h1>Genres detail</h1>
      <table class="table genres-show">

            <th>NAME</th>
            <th>作成時刻</th>
            <th>更新日時</th>
            <th></th>
         <% @genre.each do |genre| %>
            <tr>
              <td>
                  <%= genre.name %>
                </td>
              <td>

                <%= genre.created_at.strftime('%Y/%m/%d %H:%M') %>

                </td>

                <td><%= genre.updated_at %></td>

              <td><%= link_to "Edit",  edit_admin_genre_path(genre), class:"btn btn-success"%></td>

              <% end %>

          </tr>
        </table>
</div>
</div>
</div>

app/views/admin/items/edit.html.erb
<div class="container">
<h1>Admin::Items#edit</h1>
<p>Find me in app/views/admin/items/edit.html.erb</p>


  <div class="row">

   <div class="col-lx-1">
<h1>Item info</h1>

<%= form_with model:@item, url:admin_item_path, local:true do |f| %>
  <h3><%= f.label :NAME %></h3>
  <%= f.text_field :name, placeholder:"商品名" %>
  <br><br>
  <h3><%= f.label :ジャンル %></h3>

  <%= f.collection_select :genre_id, Genre.all, :id, :name %>
  <br>
  <label for="inputImage">ProfileImage</label>
  <br>

  <%= attachment_image_tag @item, :image, :fill, 60, 60, fallback: "no_image.jpg"%>

  <br>

  <br>
  <h3><%= f.label :商品説明 %></h3>
  <%= f.text_area :introduction, placeholder:"商品説明"%>
  <br>
  <h3><%= f.label :価格 %></h3>
  <%= f.text_field :price, placeholder:"価格" %>
  <br><br>
  <%= f.submit "Update" %>
<% end %>

app/views/admin/items/index.html.erb
<div class="container">
  <div class="row">
   <div class="col-md-12">
<h1>Items</h1>

      <table class="table genres-show">
        <th>商品名<br>商品画像</th>
        <th>ジャンル</th>
        <th>説明</th>
        <th>価格</th>
        <th>作成時刻</th>
        <th>更新日時</th>
        <th></th>
        <th></th>
        <% @item.each do |item| %>
        <tr>
          <td>
            <%= item.name %><br>

            <%= attachment_image_tag item, :image, :fill, 50, 50, fallback: "no_image.jpg"%>
                </td>


              <td><%= item.genre.name %></td>

              <td><%= item.introduction %></td>
              <td><%= item.price %></rd>
              <td>
                <%= item.created_at.strftime('%Y/%m/%d %H:%M') %>
                </td>
                <td><%= item.updated_at %></td>
              <td><%= link_to "show",  admin_item_path(item), class:"btn btn-info" %></td>
              <td><%= link_to "Edit",  edit_admin_item_path(item), class:"btn btn-success" %></td>

              <% end %>

            </div>
            

          </div>
            </div>
            <%= link_to "新規作成",  new_admin_item_path, class:"btn btn-primary" %>
        </div>
      

app/views/admin/items/new.html.erb
<div class="container">
  <div class="row">
   <div class="col-md-4">

<h1>New Item</h1>
<%= form_with(model:@item, url:admin_items_path(@item), method: :POST, local:true) do |f| %>


<!-- イメージ -->
  <label for="inputImage">item Image</label><br>
  <%= f.file_field :image, placeholder: "商品画像" %>
  <br>
  <br>
<!-- イメージ終わり -->
  <%= f.label :ジャンル %><br>
  <%= f.collection_select :genre_id, Genre.all, :id, :name, include_blank: "選択して下さい" %>
  <br>
  <br>

<div>
  <%= f.label :NAME %>
</div>
<div>
  <%= f.text_field :name %>
</div>
<div>
  <%= f.label :商品説明 %>
</div>
<div>
  <%= f.text_area :introduction %>

</div>
<div>
  <%= f.label :価格 %>
</div>
<div>
  <%= f.text_field :price %>

</div>
<br>
  <%= f.submit 'Create' %>

<% end %>
</div>
</div>
</div>

app/views/admin/items/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-mx-1">

      <h1>Item detail</h1>
      <p>商品名</p>
      <%= @item.name %>
      <p>ジャンル</p>
      <%= @item.genre.name %>
      <p>商品画像</p>
      <%= attachment_image_tag @item, :image, :fill, 50, 50, fallback: "no_image.jpg"%>
      <p>商品説明</p>
      <%= @item.introduction %>
      <p>価格</p>
      <%= @item.price %>
      <br>
      <%= link_to "一覧へ",  admin_items_path, class:"btn btn-primary" %>
    </div>
  </div>
</div>

app/views/admin/orders/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h1>Orders</h1>
      <h1>Orders detail</h1>
      <table class="table orders-show">
      <th>注文番号</th>
      <th>ステータス</th>
      <th>注文日時</th>
      <th>お客様</th>
      <th>配送先郵便番号</th>
      <th>合計金額</th>
      <th></th>
      <% @order.each do |order| %>
      <tr>
        <td><%= order.id %></td>
        <td><%= order.status %></td>
        <td><%= order.created_at.strftime('%Y/%m/%d %H:%M') %></td>
        <td><%= order.name %></td>
        <td><%= order.postal_code %></td>
        <td><%= order.total_payment %></td>
        <td><%= link_to "注文詳細",  admin_order_path(order), class:"btn btn-success" %></td>
        <% end %>
      </div>
    </div>
  </div>

app/views/admin/orders/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-mx-1">
      <table class="table imte">
        <h2>注文した商品</h2>
        <th>商品名<br>
        <th>単価</th>
        <th>数量</th>
        <th>合計価格</th>
        <% @order.order_details.each do |order_detail| %>
        <tr>
          <td><%= order_detail.item.name %></td>
          <td><%= order_detail.price %></td>
          <td><%= order_detail.amount %></td>
          <td><%= order_detail.amount*order_detail.price %></td>
        </tr>
        <% end %>
        </table>
    </div>
  </div>
  <div class="row">
    <div class="col-mx-1">
      <h1>Order detail</h1>
      <p>注文ID</p>
      <%= @order.id %>
      <p>会員ID</p>
      <%= @order.customer_id %>
      <p>配送先郵便番号</p>
      <%= @order.postal_code %>
      <p>配送先住所</p>
      <%= @order.address %>
      <p>配送先宛名</p>
      <%= @order.name %>
      <p>送料</p>
      <%= @order.shipping_cost %>
      <p>請求額</p>
      <%= @order.total_payment %>
      <p>支払方法</p>
      <%= @order.payment_method %>
      <p>注文ステータス</p>
      <%= @order.status %>
      <p>登録日時</p>
      <%= @order.created_at.strftime('%Y/%m/%d %H:%M') %>
      <p>更新日時</p>
      <%= @order.updated_at.strftime('%Y/%m/%d %H:%M') %>
      <br>
      <%= link_to "back", admin_orders_path, class:"btn btn-success"%>

    </div>
  </div>
</div>