config/routes.rb
Rails.application.routes.draw do

  
  namespace :public do
    get 'order_details/new'
  end
root to: 'public/homes#top'
get 'about' => 'public/homes#about'
get 'items' => 'public/items#index'
get 'items/:id' => 'public/items#show', as: 'item'
post 'cart_items' => 'public/cart_items#create'
get 'cart_items' => 'public/cart_items#index'
patch 'cart_items' => 'public/cart_items#update'

delete 'cart_items/:id' => 'public/cart_items#destroy', as: 'destroy_cart_item'
delete 'cart_items' => 'public/cart_items#destroy_all', as: 'cart_items_destroy_all'


get 'orders/new' => 'public/orders#new'
post 'orders/comfirm' => 'public/orders#comfirm'
post 'orders' => 'public/orders#create'
get 'orders/complete' => 'public/orders#complete'
get 'orders' => 'public/orders#index', as: 'orders_index'
get 'orders/:id' => 'public/orders#show', as: 'order'

  scope module: 'public' do
    get 'customers/edit/:id' => 'customers#edit', as: 'edit_customer'
    patch 'customers' => 'customers#update', as: 'customer'
    get 'customers/my_page' => 'customers#show'
    get 'customers/unsubscribe' => 'customers#unsubscribe'
    patch 'customers/withdraw'
   end
  get 'addresses' => 'public/addresses#index'
  get 'addresses/:id/edit' => 'public/addresses#edit'
  post 'addresses' => 'public/addresses#create'
  patch 'addresses/:id' => 'public/addresses#update'
  delete 'addresses/:id' => 'public/addresses#destroy'

  namespace :admin do
    get 'orders/index'
  end
#  devise_for :admins
    devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
    }
  namespace :admin do
    resources :customers, only: [:index, :show, :edit, :update]
  end
  namespace :admin do
    resources :genres
  end
  namespace :admin do
    resources :items
  end
  namespace :admin do
    get 'top' => 'homes#top'
  end
  namespace :admin do
    resources :orders
  end
  devise_for :customers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord


  belongs_to :item
  belongs_to :customer

  #def total_price
	#	line_items.to_a.sum { |item| item.total_price }
	#end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses
  has_many :orders
  has_many :cart_items
  
  def active_for_authentication?
    super && (self.is_active == false)
  end
  
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :item, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
    
    attachment :image
    belongs_to :genre,  optional: true
    has_many :cart_items
  #  has_many :orders
    has_many :order_details
end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :customer
  has_many :order_details
  enum payment_method: { クレジットカード: 0, 銀行振込: 1 }
  enum status: { 入金待ち: 0, 入金確認: 1, 製作中: 2, 発送準備中: 3, 発送済み: 4 }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @order = Order.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :postal_code, :address, :telephone_number, :is_deleted,])
  end
  
  def after_sign_in_path_for(resource)
    root_path
  end

  def after_sign_out_path_for(resource)
    root_path
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<html>
    <script src="https://kit.fontawesome.com/cc6b65f71c.js" crossorigin="anonymous"></script>
  <head>
    <title>NGANO CAKE</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

</head>
<body>
<header>
<nav class="navbar navbar-expand-lg navbar-light bg-light">

    <div class="container-fluid">
        <%= link_to root_path do %>
        <span>NAGANO CAKE</span>
        <% end %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <% if customer_signed_in? %>
                <li class="nav-item">
                    <%= link_to items_path, class:"nav-link" do %>
                    <span aria-hidden="true">商品一覧</span>
                    <% end %>
                </li>
                <li class="nav-item">
                    <%= link_to customers_my_page_path, class:"nav-link" do %>
                    <span aria-hidden="true">マイページ</span>
                    <% end %>
                </li>
                <li class="nav-item">
                    <%= link_to cart_items_path, class:"nav-link" do %>
                    <span aria-hidden="true">カート</span>
                    <% end %>
                </li>
                <li class="nav-item">
                    <%= link_to destroy_customer_session_path, method: :delete, class:"nav-link" do %>
                    <span class="fas fa-sign-out-alt" aria-hidden="true">logout</span>
                    <% end %>
                </li>
            <% elsif admin_signed_in? %>
                <li class="nav-item">
                    <i ></i>
                        <%= link_to admin_top_path, class:"nav-link" do %>
                        <span class="fas fa-home" aria-hidden="true">注文履歴一覧</span>
                        <% end %>
                </li>
                <li class="nav-item">

                        <%= link_to admin_customers_path, class:"nav-link" do %>
                        <span aria-hidden="true">会員一覧画面</span>
                        <% end %>
                </li>
                <li class="nav-item">
                        <%= link_to admin_items_path, class:"nav-link" do %>
                        <span aria-hidden="true">商品一覧</span>
                        <% end %>
                </li>
                <li class="nav-item">
                        <%= link_to destroy_admin_session_path, method: :delete, class:"nav-link" do %>
                        <span class="fas fa-sign-in-alt" aria-hidden="true">admin_logout</span>
                        <% end %>

                </li>

            <% else %>
                <li class="nav-item">
                    <i ></i>
                        <%= link_to root_path, class:"nav-link" do %>
                        <span class="fas fa-home" aria-hidden="true">Home</span>
                        <% end %>
                </li>
                <li class="nav-item">

                        <%= link_to about_path, class:"nav-link" do %>
                        <span class="fas fa-link" aria-hidden="true">About</span>
                        <% end %>
                </li>
                <li class="nav-item">
                        <%= link_to new_customer_registration_path, class:"nav-link" do %>
                        <span class="fas fa-user-plus" aria-hidden="true">sign up</span>
                        <% end %>

                </li>
                <li class="nav-item">
                        <%= link_to new_customer_session_path, class:"nav-link" do %>
                        <span class="fas fa-sign-in-alt" aria-hidden="true">login</span>
                        <% end %>

                </li>



                <% end %>
            </ul>
        </div>
    </div>

</nav>
    <% flash.each do |key, value| %>
    <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>
    </header>
    <br>
      <%= yield %>
  </body>

</html>